-- Exercicio 1 --
SELECT ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT
FROM bd_produto.Dados_produto
WHERE DESCONTO IS NULL;

-- Exercicio 2 --
SET SQL_SAFE_UPDATES = 0;
UPDATE Dados_produto
SET DESCONTO= 0
WHERE COD_PROD = 3;
UPDATE Dados_produto
SET DESCONTO= 0
WHERE COD_PROD = 5;

-- Exercicio 3 --
SELECT COD_PROD, QUANTIDADE
FROM  bd_produto.Dados_produto
WHERE DESCONTO > 10 AND DESCONTO < 20;

-- Exercicio 4 --
SELECT QUANTIDADE, VALOR_UNIT
FROM Dados_produto
WHERE COD_PROD = 2;

